spring:
  datasource:
    url: jdbc:mysql://localhost:3306/starwars?useSSl=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: starwars

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
